### ISSUE TITLE
Example usage returns `405 Method Not Allowed`

### ISSUE THREAD

**Issue by vmorris** [IBM/pyds8k#10]
I'm just getting started trying out this client so this may be entirely user error.. 

## Install pyds8k
```shell
 $ python3 -m venv pyds8k
 $ . pyds8k/bin/activate
 (pyds8k) $ pip install pyds8k
>>> OUTPUT REMOVED <<<
```

## Try example
```python
(pyds8k) $ python
Python 3.6.8 (default, Sep 26 2019, 11:57:09) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyds8k.client.ds8k.v1.client import Client
>>> restclient = Client(service_address='REDACTED', user='REDACTED', password='REDACTED')
>>> restclient.get_volumes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vmorris/pyds8k/lib64/python3.6/site-packages/pyds8k/resources/ds8k/v1/common/mixins.py", line 180, in get_volumes
    return self.all(types.DS8K_VOLUME, rebuild_url=True).list()
  File "/home/vmorris/pyds8k/lib64/python3.6/site-packages/pyds8k/base.py", line 434, in list
    return self.manager.list(**kwargs)
  File "/home/vmorris/pyds8k/lib64/python3.6/site-packages/pyds8k/resources/ds8k/v1/volumes.py", line 136, in list
    return self._list(url=url, obj_class=obj_class, body=body, **kwargs)
  File "/home/vmorris/pyds8k/lib64/python3.6/site-packages/pyds8k/base.py", line 724, in _list
    _, body = self.client.get(self.url, **kwargs)
  File "/home/vmorris/pyds8k/lib64/python3.6/site-packages/pyds8k/httpclient.py", line 230, in get
    return self.request(url, 'GET', **kwargs)
  File "/home/vmorris/pyds8k/lib64/python3.6/site-packages/pyds8k/httpclient.py", line 210, in request
    raise exceptions.raise_error(resp, body, self.service_type)
pyds8k.exceptions.MethodNotAllowed: HTTP 405 Method Not Allowed. Method Not Allowed

```

**Comment by vmorris** [comment]
While I have your attention, if you don't mind.. Am I just missing the documentation here, or does the ds8k HTTP REST API not support many operations like creating volumes? How does `pyds8k` create volumes, is it using the CLI or some other UI? Thanks :)

**Comment by 27149chen** [comment]
@vmorris, it is a ds8k rest api limitation, you are not allowed to get all volumes at once. You can get by pool/lss/host/...

**Comment by vmorris** [comment]
thanks @27149chen - that explains it.
